# docker-compose.yml

services:
  web:
    build:
      context: .
    env_file:
      - .env
    expose:
      - "8000"  # Only expose to the Nginx service
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"    # Expose port 80 for HTTP
      - "443:443"  # Expose port 443 for HTTPS (future SSL support)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: unless-stopped
