# docker-compose.yml

services:
  flaskapp:
    container_name: color-palette-app
    build:
      context: .
      # Removed invalid build args
    ports:
      - "8000:8000"  # Updated port to match Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
