services:
  flaskapp:
    container_name: color-palette-app
    build:
      context: .
      args:
        - --no-cache
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: flask run --host=0.0.0.0